services:
  main:
    container_name: dynamic-update-bot
    build: .
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - 3030:3030
    environment:
      - TOKEN
      - API_PORT
      - API_SECRET
