name: Dynamic Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest script
        run: echo "SCRIPT_PATH=$(pwd)/.github/deploy/deploy.sh" >> $GITHUB_ENV

      - name: Deploy
        working-directory: ${{ vars.BOT_DIR_PATH }}
        run: ${{ env.SCRIPT_PATH }}

    env:
      TOKEN: ${{ secrets.TOKEN }}
      API_SECRET: ${{ secrets.API_SECRET }}
