name: Dynamic Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Deploy
        run: ./.github/deploy/deploy.sh

    env:
      TOKEN: ${{ secrets.TOKEN }}
      API_SECRET: ${{ secrets.API_SECRET }}
