name: Dynamic Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Deploy
        working-directory: ${{ env.BOT_DIR_PATH }}
        run: |
          echo $BOT_DIR_PATH
          echo $(pwd)
          git pull -f
          ./.github/deploy/deploy.sh
    env:
      TOKEN: ${{ secrets.TOKEN }}
      API_SECRET: ${{ secrets.API_SECRET }}
