name: Dynamic Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Deploy
        working-directory: ${{ vars.BOT_DIR_PATH }}
        run: |
          git pull -fq
          ./.github/deploy/deploy.sh
    env:
      TOKEN: ${{ secrets.TOKEN }}
      API_SECRET: ${{ secrets.API_SECRET }}
